export const workers = [
    {
        name: 'Marek',
        surname: 'Brząkalik',
        permission: 1,
        strength: 48,
        shift: false,
    },
    {
        name: 'Władysław',
        surname: 'Zjawin',
        permission: 1,
        strength: 48,
        shift: false,
    },
    {
        name: 'Andrzej',
        surname: 'Krymiec',
        permission: 1,
        strength: 48,
        shift: false,
    },
    {
        name: 'Zbigniew',
        surname: 'Zalech',
        permission: 1,
        strength: 48,
        shift: false,
    },
    {
        name: 'Lucjan',
        surname: 'Mandla',
        permission: 1,
        strength: 48,
        shift: false,
    },
    {
        name: 'Robert',
        surname: 'Kośmider',
        permission: 1,
        strength: 48,
        shift: false,
    },
    {
        name: 'Leszek',
        surname: 'Klocek',
        permission: 1,
        strength: 48,
        shift: false,
    },
    {
        name: 'Piotr',
        surname: 'Niedziela',
        permission: 1,
        strength: 48,
        shift: false,
    },
    {
        name: 'Konrad',
        surname: 'Zarzeczny',
        permission: 3,
        strength: 48,
        shift: false,
    },
    {
        name: 'Bartosz',
        surname: 'Zalewski',
        permission: 5,
        strength: 48,
        shift: false,
    },
    {
        name: 'Arkadiusz',
        surname: 'Pikulicki',
        permission: 5,
        strength: 48,
        shift: false,
    },
    {
        name: 'Karol',
        surname: 'Zieliński',
        permission: 5,
        strength: 48,
        shift: false,
    },
    {
        name: 'Zdzisław',
        surname: 'Stryczek',
        permission: 5,
        strength: 48,
        shift: false,
    },
    {
        name: 'Paweł',
        surname: 'Sanek',
        permission: 5,
        strength: 48,
        shift: false,
    },
    {
        name: 'Adam',
        surname: 'Pańta',
        permission: 5,
        strength: 48,
        shift: false,
    },
    {
        name: 'Zdzisław',
        surname: 'Szotek',
        permission: 5,
        strength: 48,
        shift: false,
    },
    {
        name: 'Mateusz',
        surname: 'Parchański',
        permission: 5,
        strength: 48,
        shift: false,
    },
    {
        name: 'Mieczysław',
        surname: 'Kupczak',
        permission: 5,
        strength: 48,
        shift: false,
    },
    {
        name: 'Rafał',
        surname: 'Beśka',
        permission: 5,
        strength: 48,
        shift: false,
    },
    {
        name: 'Jarosław',
        surname: 'Józefowicz',
        permission: 5,
        strength: 48,
        shift: false,
    },
    {
        name: 'Artur',
        surname: 'Sobczyk',
        permission: 5,
        strength: 48,
        shift: false,
    },
    {
        name: 'Bogdan',
        surname: 'Kotoński',
        permission: 5,
        strength: 48,
        shift: false,
    },
    {
        name: 'Andrzej',
        surname: 'Smolarz',
        permission: 5,
        strength: 48,
        shift: false,
    },
    {
        name: 'Dariusz',
        surname: 'Gorys',
        permission: 5,
        strength: 48,
        shift: false,
    },
    {
        name: 'Czesław',
        surname: 'Czaja',
        permission: 5,
        strength: 48,
        shift: false,
    },
    {
        name: 'Artur',
        surname: 'Radoń',
        permission: 5,
        strength: 48,
        shift: false,
    },
    {
        name: 'Mariusz',
        surname: 'Maciaszczyk',
        permission: 5,
        strength: 48,
        shift: false,
    },
    {
        name: 'Roman',
        surname: 'Wojeciech',
        permission: 6,
        strength: 48,
        shift: false,
    },
    {
        name: 'Grzegorz',
        surname: 'Mikołajczyk',
        permission: 6,
        strength: 48,
        shift: false,
    },
    {
        name: 'Jacek',
        surname: 'Piechowiak',
        permission: 6,
        strength: 48,
        shift: false,
    },
    {
        name: 'Adam',
        surname: 'Cichocki',
        permission: 6,
        strength: 48,
        shift: false,
    },
    {
        name: 'Adam',
        surname: 'Chaber',
        permission: 6,
        strength: 48,
        shift: false,
    },
    {
        name: 'Adrian',
        surname: 'Labus',
        permission: 6,
        strength: 48,
        shift: false,
    },
    {
        name: 'Robert',
        surname: 'Malinowski',
        permission: 6,
        strength: 48,
        shift: false,
    },
    {
        name: 'Karol',
        surname: 'Białoń',
        permission: 6,
        strength: 48,
        shift: false,
    },
    {
        name: 'Duda',
        surname: 'Stanisław',
        permission: 6,
        strength: 48,
        shift: false,
    },
]
