export const workers = [
    {
        id: 0,
        name: 'Marek',
        surname: 'Brząkalik',
        strength: 48,
        holidays: [],
        permission: 1,
        preferences: [],
        shift: false,
        busy: false,
        active: true,
    },
    {
        id: 1,
        name: 'Władysław',
        surname: 'Zjawin',
        strength: 48,
        holidays: [],
        permission: 1,
        preferences: [],
        shift: false,
        busy: false,
        active: true,
    },
    {
        id: 2,
        name: 'Andrzej',
        surname: 'Krymiec',
        strength: 48,
        holidays: [],
        permission: 1,
        preferences: [],
        shift: false,
        busy: false,
        active: true,
    },
    {
        id: 3,
        name: 'Zbigniew',
        surname: 'Zalech',
        strength: 48,
        holidays: [],
        permission: 1,
        preferences: [],
        shift: false,
        busy: false,
        active: true,
    },
    {
        id: 4,
        name: 'Lucjan',
        surname: 'Mandla',
        strength: 48,
        holidays: [],
        permission: 1,
        preferences: [],
        shift: false,
        busy: false,
        active: true,
    },
    {
        id: 5,
        name: 'Robert',
        surname: 'Kośmider',
        strength: 48,
        holidays: [],
        permission: 1,
        preferences: [],
        shift: false,
        busy: false,
        active: true,
    },
    {
        id: 6,
        name: 'Leszek',
        surname: 'Klocek',
        strength: 48,
        holidays: [],
        permission: 1,
        preferences: [],
        shift: false,
        busy: false,
        active: true,
    },
    {
        id: 7,
        name: 'Piotr',
        surname: 'Niedziela',
        strength: 48,
        holidays: [],
        permission: 1,
        preferences: [],
        shift: false,
        busy: false,
        active: true,
    },
    {
        id: 8,
        name: 'Konrad',
        surname: 'Zarzeczny',
        strength: 48,
        holidays: [],
        permission: 3,
        preferences: [],
        shift: false,
        busy: false,
        active: true,
    },
    {
        id: 9,
        name: 'Bartosz',
        surname: 'Zalewski',
        strength: 48,
        holidays: [],
        permission: 5,
        preferences: [],
        shift: false,
        busy: false,
        active: true,
    },
    {
        id: 10,
        name: 'Arkadiusz',
        surname: 'Pikulicki',
        strength: 48,
        holidays: [],
        permission: 5,
        preferences: [],
        shift: false,
        busy: false,
        active: true,
    },
    {
        id: 11,
        name: 'Karol',
        surname: 'Zieliński',
        strength: 48,
        holidays: [],
        permission: 5,
        preferences: [],
        shift: false,
        busy: false,
        active: true,
    },
    {
        id: 12,
        name: 'Zdzisław',
        surname: 'Stryczek',
        strength: 48,
        holidays: [],
        permission: 5,
        preferences: [],
        shift: false,
        busy: false,
        active: true,
    },
    {
        id: 13,
        name: 'Paweł',
        surname: 'Sanek',
        strength: 48,
        holidays: [],
        permission: 5,
        preferences: [],
        shift: false,
        busy: false,
        active: true,
    },
    {
        id: 14,
        name: 'Adam',
        surname: 'Pańta',
        strength: 48,
        holidays: [],
        permission: 5,
        preferences: [],
        shift: false,
        busy: false,
        active: true,
    },
    {
        id: 15,
        name: 'Zdzisław',
        surname: 'Szotek',
        strength: 48,
        holidays: [],
        permission: 5,
        preferences: [],
        shift: false,
        busy: false,
        active: true,
    },
    {
        id: 16,
        name: 'Mateusz',
        surname: 'Parchański',
        strength: 48,
        holidays: [],
        permission: 5,
        preferences: [],
        shift: false,
        busy: false,
        active: true,
    },
    {
        id: 17,
        name: 'Mieczysław',
        surname: 'Kupczak',
        strength: 48,
        holidays: [],
        permission: 5,
        preferences: [],
        shift: false,
        busy: false,
        active: true,
    },
    {
        id: 18,
        name: 'Rafał',
        surname: 'Beśka',
        strength: 48,
        holidays: [],
        permission: 5,
        preferences: [],
        shift: false,
        busy: false,
        active: true,
    },
    {
        id: 19,
        name: 'Jarosław',
        surname: 'Józefowicz',
        strength: 48,
        holidays: [],
        permission: 5,
        preferences: [],
        shift: false,
        busy: false,
        active: true,
    },
    {
        id: 20,
        name: 'Artur',
        surname: 'Sobczyk',
        strength: 48,
        holidays: [],
        permission: 5,
        preferences: [],
        shift: false,
        busy: false,
        active: true,
    },
    {
        id: 21,
        name: 'Bogdan',
        surname: 'Kotoński',
        strength: 48,
        holidays: [],
        permission: 5,
        preferences: [],
        shift: false,
        busy: false,
        active: true,
    },
    {
        id: 22,
        name: 'Andrzej',
        surname: 'Smolarz',
        strength: 48,
        holidays: [],
        permission: 5,
        preferences: [],
        shift: false,
        busy: false,
        active: true,
    },
    {
        id: 23,
        name: 'Dariusz',
        surname: 'Gorys',
        strength: 48,
        holidays: [],
        permission: 5,
        preferences: [],
        shift: false,
        busy: false,
        active: true,
    },
    {
        id: 24,
        name: 'Czesław',
        surname: 'Czaja',
        strength: 48,
        holidays: [],
        permission: 5,
        preferences: [],
        shift: false,
        busy: false,
        active: true,
    },
    {
        id: 25,
        name: 'Artur',
        surname: 'Radoń',
        strength: 48,
        holidays: [],
        permission: 5,
        preferences: [],
        shift: false,
        busy: false,
        active: true,
    },
    {
        id: 26,
        name: 'Mariusz',
        surname: 'Maciaszczyk',
        strength: 48,
        holidays: [],
        permission: 5,
        preferences: [],
        shift: false,
        busy: false,
        active: true,
    },
    {
        id: 27,
        name: 'Roman',
        surname: 'Wojeciech',
        strength: 48,
        holidays: [],
        permission: 6,
        preferences: [],
        shift: false,
        busy: false,
        active: true,
    },
    {
        id: 28,
        name: 'Grzegorz',
        surname: 'Mikołajczyk',
        strength: 48,
        holidays: [],
        permission: 6,
        preferences: [],
        shift: false,
        busy: false,
        active: true,
    },
    {
        id: 29,
        name: 'Jacek',
        surname: 'Piechowiak',
        strength: 48,
        holidays: [],
        permission: 6,
        preferences: [],
        shift: false,
        busy: false,
        active: true,
    },
    {
        id: 30,
        name: 'Adam',
        surname: 'Cichocki',
        strength: 48,
        holidays: [],
        permission: 6,
        preferences: [],
        shift: false,
        busy: false,
        active: true,
    },
    {
        id: 31,
        name: 'Adam',
        surname: 'Chaber',
        strength: 48,
        holidays: [],
        permission: 6,
        preferences: [],
        shift: false,
        busy: false,
        active: true,
    },
    {
        id: 32,
        name: 'Adrian',
        surname: 'Labus',
        strength: 48,
        holidays: [],
        permission: 6,
        preferences: [],
        shift: false,
        busy: false,
        active: true,
    },
    {
        id: 33,
        name: 'Robert',
        surname: 'Malinowski',
        strength: 48,
        holidays: [],
        permission: 6,
        preferences: [],
        shift: false,
        busy: false,
        active: true,
    },
    {
        id: 34,
        name: 'Karol',
        surname: 'Białoń',
        strength: 48,
        holidays: [],
        permission: 6,
        preferences: [],
        shift: false,
        busy: false,
        active: true,
    },
    {
        id: 35,
        name: 'Duda',
        surname: 'Stanisław',
        strength: 48,
        holidays: [],
        permission: 6,
        preferences: [],
        shift: false,
        busy: false,
        active: true,
    },
]
